version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
